version: '3.7'
services:
  mysql:
    container_name: db-server
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userLists
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql
